package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type projectDocSpec struct {
	templateRel string
	destRel     string
	label       string
	managedFn   func(string) bool
}

func syncProjectDocs(hubSystem, repoDir string) ([]map[string]interface{}, int, int, []string) {
	specs := []projectDocSpec{
		{
			templateRel: filepath.Join("templates", "agents-md-template.md"),
			destRel:     "AGENTS.md",
			label:       "AGENTS.md",
			managedFn:   isAetherManagedAgentsDoc,
		},
		{
			templateRel: filepath.Join("templates", "codex-md-template.md"),
			destRel:     filepath.Join(".codex", "CODEX.md"),
			label:       ".codex/CODEX.md",
			managedFn:   isAetherManagedCodexDoc,
		},
		{
			templateRel: filepath.Join("templates", "opencode-md-template.md"),
			destRel:     filepath.Join(".opencode", "OPENCODE.md"),
			label:       ".opencode/OPENCODE.md",
			managedFn:   isAetherManagedOpenCodeDoc,
		},
	}

	results := make([]map[string]interface{}, 0, len(specs))
	totalCopied := 0
	totalSkipped := 0
	var errs []string

	for _, spec := range specs {
		entry, copied, skipped, err := syncManagedProjectDoc(hubSystem, repoDir, spec)
		results = append(results, entry)
		totalCopied += copied
		totalSkipped += skipped
		if err != nil {
			errs = append(errs, err.Error())
		}
	}

	return results, totalCopied, totalSkipped, errs
}

func syncManagedProjectDoc(hubSystem, repoDir string, spec projectDocSpec) (map[string]interface{}, int, int, error) {
	entry := map[string]interface{}{"label": spec.label}
	templatePath := filepath.Join(hubSystem, spec.templateRel)
	destPath := filepath.Join(repoDir, spec.destRel)

	templateBytes, err := os.ReadFile(templatePath)
	if err != nil {
		if os.IsNotExist(err) {
			entry["skipped"] = 1
			entry["reason"] = "template missing"
			return entry, 0, 1, nil
		}
		entry["errors"] = []string{err.Error()}
		return entry, 0, 0, fmt.Errorf("%s template: %w", spec.label, err)
	}

	rendered := renderProjectDocTemplate(string(templateBytes))

	existingBytes, err := os.ReadFile(destPath)
	if err == nil {
		existing := string(existingBytes)
		if existing == rendered {
			entry["skipped"] = 1
			entry["reason"] = "unchanged"
			return entry, 0, 1, nil
		}
		if !spec.managedFn(existing) {
			entry["skipped"] = 1
			entry["reason"] = "preserved local custom file"
			entry["preserved_local"] = true
			return entry, 0, 1, nil
		}
	} else if !os.IsNotExist(err) {
		entry["errors"] = []string{err.Error()}
		return entry, 0, 0, fmt.Errorf("read %s: %w", destPath, err)
	}

	if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
		entry["errors"] = []string{err.Error()}
		return entry, 0, 0, fmt.Errorf("mkdir %s: %w", filepath.Dir(destPath), err)
	}
	if err := os.WriteFile(destPath, []byte(rendered), 0644); err != nil {
		entry["errors"] = []string{err.Error()}
		return entry, 0, 0, fmt.Errorf("write %s: %w", destPath, err)
	}

	entry["copied"] = 1
	return entry, 1, 0, nil
}

func renderProjectDocTemplate(template string) string {
	template = strings.ReplaceAll(template, "{COLONY_NAME}", "")
	template = strings.ReplaceAll(template, "{COLONY_GOAL}", "")
	return template
}

func isAetherManagedAgentsDoc(content string) bool {
	return strings.Contains(content, "Aether Colony -- Codex CLI Instructions") ||
		strings.Contains(content, "Generated by Aether setup") ||
		strings.Contains(content, "All colony operations use the `aether` CLI binary directly")
}

func isAetherManagedCodexDoc(content string) bool {
	return strings.Contains(content, "Aether Codex Workflow Guide") ||
		strings.Contains(content, "Generated by Aether setup") ||
		strings.Contains(content, "This repo is Aether-enabled for Codex CLI")
}

func isAetherManagedOpenCodeDoc(content string) bool {
	return strings.Contains(content, "Aether Colony -- OpenCode Instructions") ||
		strings.Contains(content, "Generated by Aether setup") ||
		strings.Contains(content, "This repo is Aether-enabled for OpenCode")
}

func platformRestartTargets(details []map[string]interface{}) []string {
	order := []struct {
		label  string
		target string
	}{
		{label: "AGENTS.md", target: "AGENTS.md"},
		{label: ".codex/CODEX.md", target: ".codex/CODEX.md"},
		{label: "Agents (codex)", target: "Codex agents"},
		{label: "Skills (codex)", target: "Codex skills"},
		{label: ".opencode/OPENCODE.md", target: ".opencode/OPENCODE.md"},
		{label: "Agents (opencode)", target: "OpenCode agents"},
	}

	seen := make(map[string]bool, len(order))
	var targets []string
	for _, candidate := range order {
		if !assetCopied(details, candidate.label) || seen[candidate.target] {
			continue
		}
		seen[candidate.target] = true
		targets = append(targets, candidate.target)
	}
	return targets
}

func assetCopied(details []map[string]interface{}, label string) bool {
	for _, entry := range details {
		if strings.TrimSpace(stringValue(entry["label"])) != label {
			continue
		}
		if intValue(entry["copied"]) > 0 {
			return true
		}
	}
	return false
}

func platformRestartMessage(targets []string) string {
	if len(targets) == 0 {
		return ""
	}

	var codexTargets, opencodeTargets []string
	for _, t := range targets {
		if strings.HasPrefix(t, ".opencode/") || strings.HasPrefix(t, "OpenCode") {
			opencodeTargets = append(opencodeTargets, t)
		} else {
			codexTargets = append(codexTargets, t)
		}
	}

	var parts []string
	if len(codexTargets) > 0 {
		parts = append(parts, fmt.Sprintf(
			"Close this Codex chat and start a new one in this repo to load refreshed %s.",
			joinWithAnd(codexTargets),
		))
	}
	if len(opencodeTargets) > 0 {
		parts = append(parts, fmt.Sprintf(
			"Restart your OpenCode session to load refreshed %s.",
			joinWithAnd(opencodeTargets),
		))
	}
	return strings.Join(parts, " ")
}

func joinWithAnd(items []string) string {
	switch len(items) {
	case 0:
		return ""
	case 1:
		return items[0]
	case 2:
		return items[0] + " and " + items[1]
	default:
		return strings.Join(items[:len(items)-1], ", ") + ", and " + items[len(items)-1]
	}
}
