package cmd

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsAetherManagedOpenCodeDoc(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "managed with sentinel",
			content: "# Colony\n\n> Aether Colony -- OpenCode Instructions\n\nSome content",
			want:    true,
		},
		{
			name:    "managed with generated marker",
			content: "# Colony\n\n*Generated by Aether setup. Customize this file for your project.*",
			want:    true,
		},
		{
			name:    "managed with enabled marker",
			content: "# Colony\n\nThis repo is Aether-enabled for OpenCode\n",
			want:    true,
		},
		{
			name:    "not managed — custom content",
			content: "# My Project\n\nCustom OpenCode instructions\n",
			want:    false,
		},
		{
			name:    "not managed — Codex doc",
			content: "# Colony\n\n> Aether Colony -- Codex CLI Instructions\n",
			want:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isAetherManagedOpenCodeDoc(tt.content); got != tt.want {
				t.Errorf("isAetherManagedOpenCodeDoc() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestPlatformRestartTargetsIncludesOpenCode(t *testing.T) {
	details := []map[string]interface{}{
		{"label": "AGENTS.md", "copied": 1},
		{"label": ".codex/CODEX.md", "copied": 1},
		{"label": ".opencode/OPENCODE.md", "copied": 1},
	}
	targets := platformRestartTargets(details)

	foundAGENTS := false
	foundOpenCode := false
	for _, t := range targets {
		if t == "AGENTS.md" {
			foundAGENTS = true
		}
		if t == ".opencode/OPENCODE.md" {
			foundOpenCode = true
		}
	}
	if !foundAGENTS {
		t.Error("expected AGENTS.md in restart targets")
	}
	if !foundOpenCode {
		t.Error("expected .opencode/OPENCODE.md in restart targets")
	}
}

func TestPlatformRestartMessageDualPlatform(t *testing.T) {
	targets := []string{"AGENTS.md", ".codex/CODEX.md", ".opencode/OPENCODE.md"}
	msg := platformRestartMessage(targets)

	if msg == "" {
		t.Fatal("expected non-empty restart message for dual-platform targets")
	}
	codexFound := false
	opencodeFound := false
	if containsStr(msg, "Close this Codex chat") {
		codexFound = true
	}
	if containsStr(msg, "Restart your OpenCode session") {
		opencodeFound = true
	}
	if !codexFound {
		t.Error("expected Codex restart guidance in dual-platform message")
	}
	if !opencodeFound {
		t.Error("expected OpenCode restart guidance in dual-platform message")
	}
}

func TestPlatformRestartMessageOpenCodeOnly(t *testing.T) {
	targets := []string{".opencode/OPENCODE.md", "OpenCode agents"}
	msg := platformRestartMessage(targets)

	if msg == "" {
		t.Fatal("expected non-empty restart message for OpenCode-only targets")
	}
	if containsStr(msg, "Close this Codex chat") {
		t.Error("did not expect Codex guidance for OpenCode-only targets")
	}
	if !containsStr(msg, "Restart your OpenCode session") {
		t.Error("expected OpenCode restart guidance")
	}
}

func TestSyncProjectDocsGeneratesOpenCodeMD(t *testing.T) {
	hubDir := t.TempDir()
	repoDir := t.TempDir()

	// Create hub template
	templatesDir := filepath.Join(hubDir, "templates")
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		t.Fatal(err)
	}
	opencodeTemplate := "# {COLONY_NAME}\n\n> Aether Colony -- OpenCode Instructions\n\nColony goal: {COLONY_GOAL}\n\n*Generated by Aether setup. Customize this file for your project.*\n"
	if err := os.WriteFile(filepath.Join(templatesDir, "opencode-md-template.md"), []byte(opencodeTemplate), 0644); err != nil {
		t.Fatal(err)
	}

	results, copied, _, _ := syncProjectDocs(hubDir, repoDir)

	if copied == 0 {
		t.Fatal("expected at least one file to be copied")
	}

	dest := filepath.Join(repoDir, ".opencode", "OPENCODE.md")
	content, err := os.ReadFile(dest)
	if err != nil {
		t.Fatalf("OpenCode OPENCODE.md was not created: %v", err)
	}

	result := string(content)
	if containsStr(result, "{COLONY_NAME}") {
		t.Error("expected {COLONY_NAME} to be replaced")
	}
	if containsStr(result, "{COLONY_GOAL}") {
		t.Error("expected {COLONY_GOAL} to be replaced")
	}
	if !containsStr(result, "Aether Colony -- OpenCode Instructions") {
		t.Error("expected sentinel in generated file")
	}

	// Verify the result entry
	found := false
	for _, entry := range results {
		if entry["label"] == ".opencode/OPENCODE.md" {
			found = true
			if entry["copied"] != 1 {
				t.Errorf("expected copied=1, got %v", entry["copied"])
			}
		}
	}
	if !found {
		t.Error("expected .opencode/OPENCODE.md entry in results")
	}
}

func TestSyncProjectDocsPreservesCustomOpenCodeMD(t *testing.T) {
	hubDir := t.TempDir()
	repoDir := t.TempDir()

	// Create hub template
	templatesDir := filepath.Join(hubDir, "templates")
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		t.Fatal(err)
	}
	opencodeTemplate := "# Colony\n\n> Aether Colony -- OpenCode Instructions\n\nNew template content.\n"
	if err := os.WriteFile(filepath.Join(templatesDir, "opencode-md-template.md"), []byte(opencodeTemplate), 0644); err != nil {
		t.Fatal(err)
	}

	// Pre-create custom OPENCODE.md (NOT managed by Aether)
	customContent := "# My Project\n\nCustom OpenCode instructions that should be preserved.\n"
	if err := os.MkdirAll(filepath.Join(repoDir, ".opencode"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repoDir, ".opencode", "OPENCODE.md"), []byte(customContent), 0644); err != nil {
		t.Fatal(err)
	}

	_, _, skipped, _ := syncProjectDocs(hubDir, repoDir)
	if skipped == 0 {
		t.Error("expected at least one file to be skipped")
	}

	// Custom content should be preserved
	content, err := os.ReadFile(filepath.Join(repoDir, ".opencode", "OPENCODE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != customContent {
		t.Errorf("custom OPENCODE.md was overwritten\ngot:  %s\nwant: %s", string(content), customContent)
	}
}

func TestSyncProjectDocsRefreshesManagedOpenCodeMD(t *testing.T) {
	hubDir := t.TempDir()
	repoDir := t.TempDir()

	// Create hub template
	templatesDir := filepath.Join(hubDir, "templates")
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		t.Fatal(err)
	}
	newTemplate := "# Colony\n\n> Aether Colony -- OpenCode Instructions\n\nUpdated template content.\n\n*Generated by Aether setup. Customize this file for your project.*\n"
	if err := os.WriteFile(filepath.Join(templatesDir, "opencode-md-template.md"), []byte(newTemplate), 0644); err != nil {
		t.Fatal(err)
	}

	// Pre-create managed (Aether-owned) OPENCODE.md
	oldContent := "# Colony\n\n> Aether Colony -- OpenCode Instructions\n\nOld content.\n\n*Generated by Aether setup. Customize this file for your project.*\n"
	if err := os.MkdirAll(filepath.Join(repoDir, ".opencode"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repoDir, ".opencode", "OPENCODE.md"), []byte(oldContent), 0644); err != nil {
		t.Fatal(err)
	}

	_, copied, _, _ := syncProjectDocs(hubDir, repoDir)

	if copied == 0 {
		t.Fatal("expected at least one file to be copied (refreshed)")
	}

	// Verify file was updated
	content, err := os.ReadFile(filepath.Join(repoDir, ".opencode", "OPENCODE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) == oldContent {
		t.Error("managed OPENCODE.md should have been refreshed but was not")
	}
	if !containsStr(string(content), "Updated template content") {
		t.Errorf("expected updated content in OPENCODE.md, got:\n%s", string(content))
	}
}
